### ISSUE TITLE
自动执行 Actions 报错

### ISSUE THREAD

**Issue by lintstar** [JunzhouLiu/BILIBILI-HELPER#174]
Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project BILIBILI-HELPER: An exception occured while executing the Java class. null: NullPointerException -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.

**Comment by JunzhouLiu** [comment]
偶发性异常，由于网络不可达导致。Network is unreachable (connect failed)

```
org.apache.http.conn.HttpHostConnectException: Connect to api.live.bilibili.com:443 [api.live.bilibili.com/23.236.97.58, api.live.bilibili.com/2400:5280:1003:9:0:0:0:3, api.live.bilibili.com/2400:5280:1003:9:0:0:0:2, api.live.bilibili.com/2400:5280:1003:9:0:0:0:4] failed: Network is unreachable (connect failed)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at top.misec.utils.HttpUtil.doGet(HttpUtil.java:138)
	at top.misec.task.Silver2coin.run(Silver2coin.java:37)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:33)
	at top.misec.BiliMain.main(BiliMain.java:36)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Network is unreachable (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 15 more
2020-11-29 22:35:56 INFO  : 任务状态推送成功
Warning:  
java.lang.NullPointerException
    at top.misec.task.Silver2coin.run (Silver2coin.java:37)
    at top.misec.task.DailyTask.doDailyTask (DailyTask.java:33)
    at top.misec.BiliMain.main (BiliMain.java:36)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:748)
```
