### ISSUE TITLE
微信推送报错

### ISSUE THREAD

**Issue by jiuntian** [JunzhouLiu/BILIBILI-HELPER#175]
ServerPush.java:29-31
```
JsonObject jsonObject = HttpUtil.doPost(url, pushBody);
if ("success".equals(jsonObject.get("errmsg").getAsString())) {
```
当Post失败的时候 `jsonObject` 是null, `jsonObject.get("errmsg").getAsString()` 会得到 NullPointerException
也许可以改为：
```
if (jsonObject != null && "success".equals(jsonObject.get("errmsg").getAsString())) {
```
你看如何？

Stacktrace: 
```
2020-11-29 23:53:10 ERROR : javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1369)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1210)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1111)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:398)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:370)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:91)
	at top.misec.task.ServerPush.pushMsg(ServerPush.java:29)
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:41)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:39)
	at top.misec.BiliMain.main(BiliMain.java:36)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:481)
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470)
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1202)
	... 22 more
Warning:  
java.lang.NullPointerException
    at top.misec.task.ServerPush.pushMsg (ServerPush.java:31)
    at top.misec.task.ServerPush.doServerPush (ServerPush.java:41)
    at top.misec.task.DailyTask.doDailyTask (DailyTask.java:39)
    at top.misec.BiliMain.main (BiliMain.java:36)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:748)
```

**Comment by jiuntian** [comment]
SSLHandshakeException SSL的问题的话不怎么清楚

**Comment by JunzhouLiu** [comment]
@jiuntian 是的，欢迎提交PR❤

**Comment by jiuntian** [comment]
Merged.
