### ISSUE TITLE
功能：增加了每日任务开关，可临时暂停每日任务。

### ISSUE THREAD

**Issue by JunzhouLiu** [JunzhouLiu/BILIBILI-HELPER#187]
## 方案一

修改`config.json`文件，将`skipDailyTask`的值改为1即可跳过每日任务，该方式不会发起任何请求。

## 方案二

关闭GitHub actions
![image](https://user-images.githubusercontent.com/17582066/100806186-fcf4a000-346a-11eb-9231-00c6b43c346a.png)
![image](https://user-images.githubusercontent.com/17582066/100806304-2dd4d500-346b-11eb-8724-f7120572c86d.png)

**Comment by gorsonkwok** [comment]
![image](https://user-images.githubusercontent.com/43696632/107698632-c8fdec80-6cef-11eb-8ac1-bd2701ffe9a1.png)
大佬，修改为0之后，出现了这个错误，这是什么原因呢？

**Comment by JunzhouLiu** [comment]
> 个错误，这是什么原因呢？

目前是改为false

**Comment by gorsonkwok** [comment]
> > 个错误，这是什么原因呢？
> 
> 目前是改为false

是将每日任务改为跳过吗？这样就没有登录经验了

**Comment by JunzhouLiu** [comment]
> > > 个错误，这是什么原因呢？
> > 
> > 
> > 目前是改为false
> 
> 是将每日任务改为跳过吗？这样就没有登录经验了

改成true的话，会尝试投币和分享，投币数改为0则不会尝试投币。但是会尝试执行其他任务。

**Comment by gorsonkwok** [comment]
> > > > 个错误，这是什么原因呢？
> > > 
> > > 
> > > 目前是改为false
> > 
> > 
> > 是将每日任务改为跳过吗？这样就没有登录经验了
> 
> 改成true的话，会尝试投币和分享，投币数改为0则不会尝试投币。但是会尝试执行其他任务。

之前试过了，改成true以后就是变成上面那种红字的情况

**Comment by JunzhouLiu** [comment]
@gorsonkwok 你这里用的不是true或者false啊，1会导致反序列化异常，所以要使用true
![image](https://user-images.githubusercontent.com/17582066/107875956-fc15cb00-6efd-11eb-9fbb-903b06ba8aaa.png)

**Comment by gorsonkwok** [comment]
> @gorsonkwok 你这里用的不是true或者false啊，1会导致反序列化异常，所以要使用true
> ![image](https://user-images.githubusercontent.com/17582066/107875956-fc15cb00-6efd-11eb-9fbb-903b06ba8aaa.png)

好的，我先试试

**Comment by gorsonkwok** [comment]
> @gorsonkwok 你这里用的不是true或者false啊，1会导致反序列化异常，所以要使用true
> ![image](https://user-images.githubusercontent.com/17582066/107875956-fc15cb00-6efd-11eb-9fbb-903b06ba8aaa.png)

![image](https://user-images.githubusercontent.com/43696632/107876103-d1784200-6efe-11eb-83ce-1981d7e85c1e.png)
![image](https://user-images.githubusercontent.com/43696632/107876107-de953100-6efe-11eb-921b-8f7760cc0741.png)
改成false还是不行

**Comment by muxiaobai** [comment]
BILIBILI-HELPER\src\main\java\top\misec\task\DailyTask.java

jsonObject 会为空，这是接口有说明么，有时候正常有时候报错。
```
 JsonObject jsonObject = HttpUtil.doGet(ApiList.reward);
 int responseCode = jsonObject.get(statusCodeStr).getAsInt();
```
```
Exception in thread "main" java.lang.NullPointerException
	at top.misec.task.DailyTask.getDailyTaskStatus(DailyTask.java:50)
	at top.misec.task.VideoWatch.run(VideoWatch.java:33)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:33)
	at top.misec.BiliMain.main(BiliMain.java:42)
```
