### ISSUE TITLE
 通过server酱推送执行结果到微信有的时候会失败。

### ISSUE THREAD

**Issue by yuhui0531** [JunzhouLiu/BILIBILI-HELPER#231]
有一天没有收到server酱推送执行结果的通知，还以为是自己的NAS挂了呢。查看日志发现是发信息到server酱的时候失败了。建议加上重试机制，比如推送失败后，过一段时间再尝试重新推送。比如加上重试次数和重试间隔。

**Comment by JunzhouLiu** [comment]
server酱推送确实会有一定几率推送失败，建议收到。近期会着手解决。

**Comment by JunzhouLiu** [comment]
@yuhui0531 可否提供一份server酱推送失败的日志。

**Comment by yuhui0531** [comment]
久等了: (

错误日志如下：
```
2020-12-06 01:44:54 ERROR : javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1369)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1210)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1111)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:398)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:370)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:100)
2020-12-06 01:44:54 INFO  : 任务状态推送失败
	at top.misec.task.ServerPush.pushMsg(ServerPush.java:40)
	at top.misec.task.ServerPush.doServerPush(ServerPush.java:23)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:67)
	at top.misec.BiliMain.main(BiliMain.java:38)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:481)
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470)
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1202)
	... 22 more
2020-12-06 01:44:54 DEBUG : null
```

简单的重试逻辑如下:
```java
        do {
            JsonObject jsonObject = HttpUtil.doPost(url, pushBody);
            if (jsonObject != null && "success".equals(jsonObject.get("errmsg").getAsString())) {
                logger.info("任务状态推送成功");
                break;
            } else {
                time++;
                LockSupport.parkNanos(TimeUnit.MINUTES.toNanos(1));
                logger.info("任务状态推送失败, retrying..." + time);
            }
        } while (time < retryTimes);
```

**Comment by JunzhouLiu** [comment]
收到，我先找找什么原因导致的。

**Comment by JunchengL** [comment]
我今天也推送失败了 不过是DNS有问题 2020-12-14 01:56:44 ERROR : java.net.UnknownHostException: sc.ftqq.com: Temporary failure in name resolution

**Comment by jiuntian** [comment]
今天得到一个timeout

**Comment by JunzhouLiu** [comment]
> 今天得到一个timeout 

这个问题可能是server酱/网络的问题。

**Comment by yuhui0531** [comment]
> > 今天得到一个timeout
> 
> 这个问题可能是server酱/网络的问题。

是的，由于server酱是部署在新浪云上的，短时间的网络闪断可能会导致类似的问题。为了避免因为网络闪断而导致消息推送失败，一般可以通过重试来尽量避免。原因是这些云服务商的反应都很快，一有问题能够在很短的时间内解决。

**Comment by zwy99** [comment]
请问能否添加server酱的那个测试号的版本？

**Comment by JunzhouLiu** [comment]
> 请问能否添加server酱的那个测试号的版本？

稍后我看下。

**Comment by JunzhouLiu** [comment]
> > > 今天得到一个timeout
> > 
> > 
> > 这个问题可能是server酱/网络的问题。
> 
> 是的，由于server酱是部署在新浪云上的，短时间的网络闪断可能会导致类似的问题。为了避免因为网络闪断而导致消息推送失败，一般可以通过重试来尽量避免。原因是这些云服务商的反应都很快，一有问题能够在很短的时间内解决。

目前已经在当前版本中抓异常了，到时候处理下。

**Comment by goukey** [comment]
今天推送又失败了

**Comment by JunzhouLiu** [comment]
> 今天推送又失败了

看到错误日志了，已记录。后续会支持钉钉推送。

**Comment by Rayzggz** [comment]
> > 今天推送又失败了
> 
> 看到错误日志了，已记录。似乎是方糖或者actions机器网络的问题，后续会支持钉钉推送。
> 
> ```
> 2021-01-18 11:34:46 ERROR : org.apache.http.conn.ConnectTimeoutException: Connect to sc.ftqq.com:443 [sc.ftqq.com/220.181.136.120] failed: Read timed out
> org.apache.http.conn.ConnectTimeoutException: Connect to sc.ftqq.com:443 [sc.ftqq.com/220.181.136.120] failed: Read timed out
> 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
> 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
> 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
> 2021-01-18 11:34:46 INFO  : [TLSv1.3, TLSv1.2, TLSv1.1, TLSv1, SSLv3, SSLv2Hello]
> 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
> 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
> 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
> 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
> 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
> 	at top.misec.utils.HttpUtil.doPost(HttpUtil.java:99)
> 	at top.misec.task.ServerPush.pushMsg(ServerPush.java:35)
> 	at top.misec.task.ServerPush.doServerPush(ServerPush.java:52)
> 	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:51)
> 	at top.misec.BiliMain.main(BiliMain.java:36)
> 	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.net.SocketTimeoutException: Read timed out
> 	at java.net.SocketInputStream.socketRead0(Native Method)
> 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
> 	at java.net.SocketInputStream.read(SocketInputStream.java:171)
> 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
> 	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:476)
> 	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470)
> 	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
> 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
> 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1202)
> 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1111)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:398)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:370)
> 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
> 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
> 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
> 	... 16 more
> 2021-01-18 11:34:46 INFO  : [TLSv1.3, TLSv1.2, TLSv1.1, TLSv1, SSLv2Hello]
> 2021-01-18 11:34:46 INFO  : 任务状态推送失败
> ```

最近的推送失败是server酱的问题

https://weibo.com/1088413295/JDqyatOic?from=page_1005051088413295_profile&wvr=6&mod=weibotime

**Comment by JunzhouLiu** [comment]
这个问题基本上是server酱的服务波动引起的，目前推送失败时会重试3次。
