### ISSUE TITLE
docker版日志提示“出了一些问题，请在自定义配置中更换UA“

### ISSUE THREAD

**Issue by jenova384** [JunzhouLiu/BILIBILI-HELPER#311]
### 错误描述
> 你所遇到的错误是怎么样的?

如下图，运行docker版日志提示“出了一些问题，请在自定义配置中更换UA”，尝试过换了所有提供的UA，包括自己浏览器的UA都没有效果。

### 错误提示和日志内容
> 最好提供错误格式和日志，如果不熟悉编程语言，请提供完整的日志。
![image](https://user-images.githubusercontent.com/76606367/107013713-ab9fbe80-67d5-11eb-9c39-09cc58370d14.png)
### 使用的版本信息
> 提供出现这个问题的程序版本号，或着git hash
docker 1.3.6版
### 使用环境
> 是在什么环境下出现的这个问题，Actions，Linux还是windows或者其他
unraid系统docker下

**Comment by JunzhouLiu** [comment]
问题收到，看上去像是接口调整造成的npe

**Comment by yaotutu** [comment]
* linux 可执行文件版遇到了同样的问题。日志如下。
* 之前用的版本是1.27，出现了一些问题，尝试更新到了1.3.6出现了同样的问题。
* 我的系统信息如下
  ```
  Distributor ID:	Ubuntu
  Description:	Ubuntu 18.04.5 LTS
  Release:	18.04
  Codename:	bionic
  ```

```
2021-02-06 12:07:16 INFO  : -----版本信息-----
2021-02-06 12:07:16 INFO  : 当前版本: 1.3.6
2021-02-06 12:07:16 INFO  : 版本更新内容:
1. 增加预留硬币数配置，当硬币余额低于配置的值时，则不会进行投币。
2021-02-06 12:07:16 INFO  : 最后更新日期: 2021-01-16
2021-02-06 12:07:16 INFO  : 项目开源地址: https://github.com/JunzhouLiu/BILIBILI-HELPER
2021-02-06 12:07:16 INFO  : -----版本信息-----
2021-02-06 12:07:16 INFO  : 读取外部配置文件成功
2021-02-06 12:07:16 INFO  : 配置信息{每日投币数为：5分享时是否点赞：0月底是否充电：true执行app客户端操作的系统是：ios投币策略：1
UA是：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 Edg/86.0.622.69
是否跳过每日任务：false}
2021-02-06 12:07:16 INFO  : 2021-02-06 12:07:16
2021-02-06 12:07:16 DEBUG : 任务启动中
2021-02-06 12:07:16 INFO  : ------登录检查开始------
2021-02-06 12:07:18 INFO  : Cookies有效，登录成功
2021-02-06 12:07:18 INFO  : 用户名称: 垚*
2021-02-06 12:07:18 INFO  : 硬币余额: 720.2
2021-02-06 12:07:18 INFO  : ------登录检查结束------
2021-02-06 12:07:18 INFO  : -----随机暂停4495ms-----
2021-02-06 12:07:22 INFO  : ------观看分享视频开始------
2021-02-06 12:07:23 INFO  : 出了一些问题，请在自定义配置中更换UA
2021-02-06 12:07:23 INFO  : 任务状态推送成功
Exception in thread "main" java.lang.NullPointerException
	at top.misec.task.DailyTask.getDailyTaskStatus(DailyTask.java:62)
	at top.misec.task.VideoWatch.run(VideoWatch.java:30)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:42)
	at top.misec.BiliMain.main(BiliMain.java:36)
```
```
2021-02-06 11:50:00 INFO  : -----版本信息-----
2021-02-06 11:50:00 INFO  : 当前版本: 1.2.7
2021-02-06 11:50:00 INFO  : 版本更新内容: 1. 优化功能任务
2021-02-06 11:50:00 INFO  : 最后更新日期: 2020-12-28
2021-02-06 11:50:00 INFO  : 项目开源地址: https://github.com/JunzhouLiu/BILIBILI-HELPER
2021-02-06 11:50:00 INFO  : -----版本信息-----

2021-02-06 11:50:00 INFO  : 未扫描到外部配置文件，即将加载默认配置文件【此提示仅针自行部署的Linux用户，普通用户请忽略】
2021-02-06 11:50:00 INFO  : 读取配置文件成功
2021-02-06 11:50:00 INFO  : 配置信息{每日投币数为：5分享时是否点赞：0月底是否充电：true执行app客户端操作的系统是：ios投币策略：1
UA是：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15
是否跳过每日任务：0}
2021-02-06 11:50:00 INFO  : 2021-02-06 11:50:00
2021-02-06 11:50:00 DEBUG : 任务启动中
2021-02-06 11:50:00 INFO  : -----登录检查开始-----
2021-02-06 11:50:03 INFO  : Cookies有效，登录成功
2021-02-06 11:50:03 INFO  : 用户名称: 垚*
2021-02-06 11:50:03 INFO  : 硬币余额: 720.2
2021-02-06 11:50:03 INFO  : -----任务结束-----

2021-02-06 11:50:03 INFO  : -----随机暂停2874ms-----

2021-02-06 11:50:06 INFO  : -----观看分享视频开始-----
2021-02-06 11:50:06 INFO  : 出了一些问题，请在自定义配置中更换UA
2021-02-06 11:50:06 INFO  : 任务状态推送成功
Exception in thread "main" java.lang.NullPointerException
	at top.misec.task.DailyTask.getDailyTaskStatus(DailyTask.java:53)
	at top.misec.task.VideoWatch.run(VideoWatch.java:33)
	at top.misec.task.DailyTask.doDailyTask(DailyTask.java:33)
	at top.misec.BiliMain.main(BiliMain.java:37)
```

**Comment by JunzhouLiu** [comment]
https://github.com/JunzhouLiu/BILIBILI-HELPER/issues/313#issuecomment-773947440
