### ISSUE TITLE
云函数执行失败

### ISSUE THREAD

**Issue by xiaoyaolanyun** [JunzhouLiu/BILIBILI-HELPER#457]
ERROR RequestId:fe3e9aa4-f1e4-4adc-801f-43bafb89e7dc Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"java.lang.reflect.InvocationTargetException","statusCode":430}

END RequestId:fe3e9aa4-f1e4-4adc-801f-43bafb89e7dc

**Comment by xiaoyaolanyun** [comment]
部署版本：BILIBILI-HELPER-v1.0.0
执行方法：top.misec.BiliMain::mainHandler
运行环境：java 8

**Comment by itning** [comment]
[更新到最新版试下](https://github.com/JunzhouLiu/BILIBILI-HELPER/releases/tag/V1.0.1)

**Comment by xiaoyaolanyun** [comment]
> [更新到最新版试下](https://github.com/JunzhouLiu/BILIBILI-HELPER/releases/tag/V1.0.1)

已经更新最新的版本 还是出现之前的错误 我看是json包报的错误 Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 9 path $.

**Comment by xiaoyaolanyun** [comment]
START RequestId:a54a3cbf-4c04-4616-8d72-e8bc0bed40fc

java.lang.reflect.InvocationTargetException

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  at java.lang.reflect.Method.invoke(Method.java:497)

  at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:225)

  at bootstrap.eventInvoke(bootstrap.java:164)

  at bootstrap.main(bootstrap.java:229)

Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 9 path $.“

  at com.google.gson.Gson.fromJson(Gson.java:942)

  at com.google.gson.Gson.fromJson(Gson.java:892)

  at com.google.gson.Gson.fromJson(Gson.java:841)

  at com.google.gson.Gson.fromJson(Gson.java:813)

  at top.misec.BiliMain.mainHandler(BiliMain.java:81)

  ... 7 more

Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 9 path $.“

  at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)

  at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:530)

  at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1232)

  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)

  at com.google.gson.Gson.fromJson(Gson.java:927)

  ... 11 more

java.lang.reflect.InvocationTargetException

  at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:235)

  at bootstrap.eventInvoke(bootstrap.java:164)

  at bootstrap.main(bootstrap.java:229)

Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 9 path $.“

  at com.google.gson.Gson.fromJson(Gson.java:942)

  at com.google.gson.Gson.fromJson(Gson.java:892)

  at com.google.gson.Gson.fromJson(Gson.java:841)

  at com.google.gson.Gson.fromJson(Gson.java:813)

  at top.misec.BiliMain.mainHandler(BiliMain.java:81)

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  at java.lang.reflect.Method.invoke(Method.java:497)

Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 9 path $.“

  at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)

  at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:530)

  at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1232)

  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)

  at com.google.gson.Gson.fromJson(Gson.java:927)

  ... 8 more

ERROR RequestId:a54a3cbf-4c04-4616-8d72-e8bc0bed40fc Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"java.lang.reflect.InvocationTargetException","statusCode":430}

END RequestId:a54a3cbf-4c04-4616-8d72-e8bc0bed40fc

Report RequestId:a54a3cbf-4c04-4616-8d72-

**Comment by itning** [comment]
这边看堆栈 是 环境变量config的值JSON反序列化失败 可以用JSON验证工具验证下 JSON格式是否有误

**Comment by xiaoyaolanyun** [comment]
好的 多谢啦

**Comment by itning** [comment]
> 好的 多谢啦

加群沟通 速度可以快一些

**Comment by insoxin** [comment]
> 这边看堆栈 是 环境变量config的值JSON反序列化失败 可以用JSON验证工具验证下 JSON格式是否有误

telegrambottoken 每个token里面有个  :   示范没引号所以报错的,可以更新下文档

**Comment by itning** [comment]
#460
