### ISSUE TITLE
赠送礼物失败

### ISSUE THREAD

**Issue by bilibiliTask** [JunzhouLiu/BILIBILI-HELPER#469]
------B站直播送出即将过期的礼物开始------

💔赠送礼物异常 : 

java.lang.IllegalStateException: Not a JSON Array: null
  at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:107) ~[user/:?]
  at top.misec.task.GiveGift.xliveGiftBagList(GiveGift.java:143) ~[user/:?]
  at top.misec.task.GiveGift.run(GiveGift.java:41) [user/:?]
  at top.misec.task.DailyTask.doDailyTask(DailyTask.java:65) [user/:?]
  at top.misec.BiliMain.mainHandler(BiliMain.java:107) [user/:?]
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
  at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
  at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:225) [ScfInternal-1.0.jar:?]
  at bootstrap.eventInvoke(bootstrap.java:165) [java8/:?]
  at bootstrap.main(bootstrap.java:230) [java8/:?]
------B站直播送出即将过期的礼物结束------

**Comment by JunzhouLiu** [comment]
小问题，不影响哈。
