### ISSUE TITLE
大佬 日志报错，7.11的日志一切正常 7.12开始报错

### ISSUE THREAD

**Issue by matocool** [JunzhouLiu/BILIBILI-HELPER#479]
������赠送礼物异常 : 

java.lang.IllegalStateException: Not a JSON Array: null

at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:107)

at top.misec.task.GiveGift.xliveGiftBagList(GiveGift.java:142)

at top.misec.task.GiveGift.run(GiveGift.java:40)

at top.misec.task.DailyTask.doDailyTask(DailyTask.java:63)

at top.misec.BiliMain.mainHandler(BiliMain.java:98)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:497)

at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:225)

at bootstrap.eventInvoke(bootstrap.java:165)

at bootstrap.main(bootstrap.java:230)

**Comment by matocool** [comment]
2021-07-12 13:49:30 INFO  : ------银瓜子换硬币开始------

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 9 path $

at com.google.gson.JsonParser.parse(JsonParser.java:65)

at com.google.gson.JsonParser.parse(JsonParser.java:45)

at top.misec.utils.HttpUtil.processResult(HttpUtil.java:155)

at top.misec.utils.HttpUtil.doGet(HttpUtil.java:135)

at top.misec.utils.HttpUtil.doGet(HttpUtil.java:106)

at top.misec.task.Silver2coin.run(Silver2coin.java:32)

at top.misec.task.DailyTask.doDailyTask(DailyTask.java:63)

at top.misec.BiliMain.mainHandler(BiliMain.java:98)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:497)

at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:225)

at bootstrap.eventInvoke(bootstrap.java:165)

at bootstrap.main(bootstrap.java:230)

Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 9 path $

at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)

at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)

at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)

at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)

at com.google.gson.JsonParser.parse(JsonParser.java:60)

... 14 more

本次执行推送日志到Server酱Turbo版本

超过当天的发送次数限制[10]，请稍后再试

任务状态推送成功

java.lang.reflect.InvocationTargetException

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:497)

at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:225)

at bootstrap.eventInvoke(bootstrap.java:165)

at bootstrap.main(bootstrap.java:230)

Caused by: java.lang.NullPointerException

at top.misec.task.Silver2coin.run(Silver2coin.java:33)

at top.misec.task.DailyTask.doDailyTask(DailyTask.java:63)

at top.misec.BiliMain.mainHandler(BiliMain.java:98)

... 7 more

java.lang.reflect.InvocationTargetException

at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:235)

at bootstrap.eventInvoke(bootstrap.java:165)

at bootstrap.main(bootstrap.java:230)

Caused by: java.lang.NullPointerException

at top.misec.task.Silver2coin.run(Silver2coin.java:33)

at top.misec.task.DailyTask.doDailyTask(DailyTask.java:63)

at top.misec.BiliMain.mainHandler(BiliMain.java:98)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:497)

ERROR RequestId:b3740e1d-7ef7-4186-bfd3-689107d6eafb Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"java.lang.reflect.InvocationTargetException","statusCode":430}

END RequestId:b3740e1d-7ef7-4186-bfd3-689107d6eafb

Report RequestId:b3740e1d-7ef7-4186-bfd3-689107d6eafb Duration:63386ms Memory:128MB MemUsage:128.000000MB

**Comment by JunzhouLiu** [comment]
版本是？

**Comment by matocool** [comment]
> 版本是？

当前版本: 1.0.0    我下载下来的版本是1.0.0 使用的也是

1.0.2 不知道哪里下。 我使用的是TX云函数



然后他这个报错有两种，我上图，大佬看看


![失败](https://user-images.githubusercontent.com/83129369/125750306-cd8d18d6-975a-4482-b329-e33c26610c33.png)
![失败20](https://user-images.githubusercontent.com/83129369/125750330-a14440ec-ad8d-4a6c-845e-eda580ff0d4c.png)

**Comment by matocool** [comment]
然后这个是正常成功的日志。成功的日志我看了下没有任何报错。没问题。

但是明明我什么都没动，他却会自动报错。但是bilibili那边经验之类的还是会获得。但是我很奇怪为啥会报错。

dedeuserid": "     "sessdata":     "biliJct":    三项数据我都检查了并且重新填入了还是这样。




![QQ图片20210715154702](https://user-images.githubusercontent.com/83129369/125750404-5d1372f0-4f61-4da5-9bca-a04f2c80e2c0.png)

**Comment by JunzhouLiu** [comment]
更新到1.0.3就好了 GitHub release页面可以下载 发件人: matocool ***@***.***>日期: 星期四, 2021年7月15日 下午3:50收件人: JunzhouLiu/BILIBILI-HELPER ***@***.***>抄送: Junzhou Liu ***@***.***>, Comment ***@***.***>主题: Re: [JunzhouLiu/BILIBILI-HELPER] 大佬 日志报错，7.11的日志一切正常 7.12开始报错 (#479)版本是？当前版本: 1.0.0 我下载下来的版本是1.0.0 使用的也是1.0.2 不知道哪里下。 我使用的是TX云函数然后他这个报错有两种，我上图，大佬看看—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by matocool** [comment]
> 更新到1.0.3就好了 GitHub release页面可以下载发件人：matocool ***@***. ***>日期：版权，2021年7月15日下午3:50发表：JunzhouLiu/BILIBILI-HELPER ***@***.***>发送：Junzhou Liu***@** *.***>, Comment ***@***.***> 主题: Re: [JunzhouLiu/BILIBILI-HELPER]大佬日志，7.11的日志正常7.[](https://github.com/JunzhouLiu/BILIBILI-HELPER/issues/479))版本是？ 当前版本: 1.0.0 我下载下来的版本是1.0.0 使用的也是1.0.2 不知道在哪里下。佬看看——你收到这个是因为你发表了评论。直接回复这封邮件，在 GitHub 上查看，或者退订。

感谢大佬，问题已解决。原来是版本的问题，之前看了下确实是兑换瓜子那边出错。

顺便请问下大佬，可否把推送到手机的的日志稍微排版下。最下面一排是一团挤在一起。看的很难受。如果能加上换行以及分割线体验会好很多，当然，这不是必备的。

谢谢大佬为项目的付出~

**Comment by matocool** [comment]
> 更新到1.0.3就好了GitHub页面可以下载发件人：matocool ***@***. ***>日期：版权，2021年7月15日下午3:50 发表：JunzhouLiu/BILIBILI-HELPER ***@***.***>发送：Junzhou Liu***@** *.* **>，评论***@***.***> 主题：回复：[JunzhouLiu/BILIBILI-HELPER]大佬日志，7.11的日志正常7.[](https://github.com/JunzhouLiu/BILIBILI-HELPER/issues/479))版本是？ 当前版本：1.0.0 我下载的这个版本是1.0.0 使用的也是1.0.2 不知道下哪里。大佬看看——你收到是因为你发表了评论。直接回复这封邮件，在GitHub上查看，或者退订。

感谢大佬，问题已解决。是版本的问题，之前的日志看了下确实是兑换瓜子出现的问题。

顺便打扰下大佬，可否把推送到手机的日志排版下。推送的前段部分还好。最下面是一堆结果是挤在一起的。看的难受。如果能加上换行和分割线体验会好很多，当然，这不是必备的。

谢谢大佬为项目的付出~
