### ISSUE TITLE
腾讯云部署报错

### ISSUE THREAD

**Issue by xwb2000** [JunzhouLiu/BILIBILI-HELPER#483]
报这个错误

START RequestId:ccac6c15-2607-4191-8b66-0feed4426df6

java.lang.reflect.InvocationTargetException

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  at java.lang.reflect.Method.invoke(Method.java:497)

  at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:225)

  at bootstrap.eventInvoke(bootstrap.java:165)

  at bootstrap.main(bootstrap.java:230)

Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 534 path $.biliJct

  at com.google.gson.Gson.fromJson(Gson.java:942)

  at com.google.gson.Gson.fromJson(Gson.java:892)

  at com.google.gson.Gson.fromJson(Gson.java:841)

  at com.google.gson.Gson.fromJson(Gson.java:813)

  at top.misec.BiliMain.mainHandler(BiliMain.java:80)

  ... 7 more

Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 534 path $.biliJct

  at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)

  at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)

  at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)

  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)

  at com.google.gson.Gson.fromJson(Gson.java:927)

  ... 11 more

java.lang.reflect.InvocationTargetException

  at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:235)

  at bootstrap.eventInvoke(bootstrap.java:165)

  at bootstrap.main(bootstrap.java:230)

Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 534 path $.biliJct

  at com.google.gson.Gson.fromJson(Gson.java:942)

  at com.google.gson.Gson.fromJson(Gson.java:892)

  at com.google.gson.Gson.fromJson(Gson.java:841)

  at com.google.gson.Gson.fromJson(Gson.java:813)

  at top.misec.BiliMain.mainHandler(BiliMain.java:80)

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  at java.lang.reflect.Method.invoke(Method.java:497)

Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 534 path $.biliJct

  at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)

  at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)

  at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)

  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)

  at com.google.gson.Gson.fromJson(Gson.java:927)

  ... 8 more

ERROR RequestId:ccac6c15-2607-4191-8b66-0feed4426df6 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"java.lang.reflect.InvocationTargetException","statusCode":430}

END RequestId:ccac6c15-2607-4191-8b66-0feed4426df6

Report RequestId:ccac6c15-2607-4191-8b66-0feed4426df6 Duration:1324ms Memory:256MB MemUsage:85.222656MB

**Comment by JunzhouLiu** [comment]
看上去是配置文件反序列化的问题，检查下配置文件的json格式。

**Comment by kanxinqing147** [comment]
自动生成的那个json是错误的，应该把文章中那种样式修改一下去用
![2021-7-21 17-38-17.png](https://i.loli.net/2021/07/21/SM2GcC7ihBL3ZPK.png)

**Comment by xwb2000** [comment]
弄好了😙我加了server的key，前面一行忘了加逗号😢------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月21日(星期三) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JunzhouLiu/BILIBILI-HELPER] 腾讯云部署报错 (#483)

**Comment by xwb2000** [comment]
> 看上去是配置文件反序列化的问题，检查下配置文件的json格式。

可以了  应该是我加了server的推送，前面一行没加逗号分隔
