### ISSUE TITLE
云部署报错

### ISSUE THREAD

**Issue by ZoinkCN** [JunzhouLiu/BILIBILI-HELPER#484]
START RequestId:e96a7360-f18b-481a-95e6-bd298f556ab6

环境信息：

KeyValueClass(dedeuserid=27698532, sessdata=59cc3cca%2C1637415351%2C000d7%2A51, biliJct=e7a91221de1561b24772a571ca0d8ed4, serverpushkey=SCT55454TfZogLAnbtkcx9r2XxbIBBMnb, telegrambottoken=null, telegramchatid=null, numberOfCoins=5, reserveCoins=50, selectLike=0, monthEndAutoCharge=true, giveGift=true, upLive=0, chargeForLove=0, devicePlatform=ios, coinAddPriority=1, skipDailyTask=false, userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15)

-----版本信息-----

当前版本: 1.0.0

版本更新内容: 1.缩小jar包体积。

2.以前投币都是从热榜获取，目前投币有一定几率会投给项目贡献者。

3.修复日志等级，默认开启每日任务。

最后更新日期: 2021-04-28

项目开源地址: https://github.com/JunzhouLiu/BILIBILI-HELPER

-----版本信息-----

配置信息{每日投币数为：5分享时是否点赞：0月底是否充电：true执行app客户端操作的系统是：ios投币策略：1

UA是：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15

是否跳过每日任务：false}

2021-07-21 00:52:08 INFO  : 2021-07-20 16:52:08

2021-07-21 00:52:08 DEBUG : 任务启动中

2021-07-21 00:52:08 INFO  : ------登录检查开始------

Cookies有效，登录成功

用户名称: あ**者ぺ

硬币余额: 1259.0

2021-07-21 00:52:11 INFO  : ------登录检查结束------

2021-07-21 00:52:11 INFO  : -----随机暂停2748ms-----

2021-07-21 00:52:13 INFO  : ------硬币情况统计开始------

2021-07-21 00:52:13 INFO  : 最近一周共计13条硬币记录

2021-07-21 00:52:13 INFO  : 最近一周收入8.0个硬币

2021-07-21 00:52:13 INFO  : 最近一周支出-5.0个硬币

2021-07-21 00:52:13 INFO  : ------硬币情况统计结束------

2021-07-21 00:52:13 INFO  : -----随机暂停3236ms-----

2021-07-21 00:52:17 INFO  : ------大会员月底B币券充电和月初大会员权益领取开始------

你配置的充电对象是你本人没错了！

今天是本月的第: 21天，还没到充电日子呢

2021-07-21 00:52:17 INFO  : ------大会员月底B币券充电和月初大会员权益领取结束------

2021-07-21 00:52:17 INFO  : -----随机暂停2873ms-----

2021-07-21 00:52:20 INFO  : ------观看分享视频开始------

2021-07-21 00:52:20 INFO  : 请求本日任务完成状态成功

本日观看视频任务已经完成了，不需要再观看视频了

视频: 街憬: 《有点衰》原神玩家倒霉图鉴 分享成功

2021-07-21 00:52:20 INFO  : ------观看分享视频结束------

2021-07-21 00:52:20 INFO  : -----随机暂停2816ms-----

2021-07-21 00:52:23 INFO  : ------B站直播送出即将过期的礼物开始------

������赠送礼物异常 : 

java.lang.IllegalStateException: Not a JSON Array: null

  at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:107)

  at top.misec.task.GiveGift.xliveGiftBagList(GiveGift.java:142)

  at top.misec.task.GiveGift.run(GiveGift.java:40)

  at top.misec.task.DailyTask.doDailyTask(DailyTask.java:63)

  at top.misec.BiliMain.mainHandler(BiliMain.java:98)

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  at java.lang.reflect.Method.invoke(Method.java:497)

  at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:225)

  at bootstrap.eventInvoke(bootstrap.java:165)

  at bootstrap.main(bootstrap.java:230)

2021-07-21 00:52:23 INFO  : ------B站直播送出即将过期的礼物结束------

2021-07-21 00:52:23 INFO  : -----随机暂停1985ms-----

2021-07-21 00:52:25 INFO  : ------漫画权益领取开始------

本日非领取大会员漫画执行日期

开始领取年度大会员权益

2021-07-21 00:52:25 INFO  : ------漫画权益领取结束------

2021-07-21 00:52:25 INFO  : -----随机暂停4087ms-----

2021-07-21 00:52:29 INFO  : ------投币任务开始------

自定义投币数为: 5枚,程序执行前已投: 5枚

已完成设定的投币任务，今日无需再投币了

投币前余额为 : 1259.0

投币任务完成后余额为: 1259.0

2021-07-21 00:52:30 INFO  : ------投币任务结束------

2021-07-21 00:52:30 INFO  : -----随机暂停1854ms-----

2021-07-21 00:52:31 INFO  : ------直播签到开始------

2021-07-21 00:52:32 INFO  : ------直播签到结束------

2021-07-21 00:52:32 INFO  : -----随机暂停2790ms-----

2021-07-21 00:52:34 INFO  : ------漫画签到开始------

完成漫画签到

2021-07-21 00:52:34 INFO  : ------漫画签到结束------

2021-07-21 00:52:34 INFO  : -----随机暂停3642ms-----

2021-07-21 00:52:38 INFO  : ------银瓜子换硬币开始------

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 9 path $

  at com.google.gson.JsonParser.parse(JsonParser.java:65)

  at com.google.gson.JsonParser.parse(JsonParser.java:45)

  at top.misec.utils.HttpUtil.processResult(HttpUtil.java:155)

  at top.misec.utils.HttpUtil.doGet(HttpUtil.java:135)

  at top.misec.utils.HttpUtil.doGet(HttpUtil.java:106)

  at top.misec.task.Silver2coin.run(Silver2coin.java:32)

  at top.misec.task.DailyTask.doDailyTask(DailyTask.java:63)

  at top.misec.BiliMain.mainHandler(BiliMain.java:98)

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  at java.lang.reflect.Method.invoke(Method.java:497)

  at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:225)

  at bootstrap.eventInvoke(bootstrap.java:165)

  at bootstrap.main(bootstrap.java:230)

Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 9 path $

  at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)

  at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)

  at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)

  at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)

  at com.google.gson.JsonParser.parse(JsonParser.java:60)

  ... 14 more

本次执行推送日志到Server酱Turbo版本

任务状态推送成功

java.lang.reflect.InvocationTargetException

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  at java.lang.reflect.Method.invoke(Method.java:497)

  at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:225)

  at bootstrap.eventInvoke(bootstrap.java:165)

  at bootstrap.main(bootstrap.java:230)

Caused by: java.lang.NullPointerException

  at top.misec.task.Silver2coin.run(Silver2coin.java:33)

  at top.misec.task.DailyTask.doDailyTask(DailyTask.java:63)

  at top.misec.BiliMain.mainHandler(BiliMain.java:98)

  ... 7 more

java.lang.reflect.InvocationTargetException

  at scfinternal.EventHandlerLoader$BaseMethodRequestHandler.handlerRequest(EventHandlerLoader.java:235)

  at bootstrap.eventInvoke(bootstrap.java:165)

  at bootstrap.main(bootstrap.java:230)

Caused by: java.lang.NullPointerException

  at top.misec.task.Silver2coin.run(Silver2coin.java:33)

  at top.misec.task.DailyTask.doDailyTask(DailyTask.java:63)

  at top.misec.BiliMain.mainHandler(BiliMain.java:98)

  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  at java.lang.reflect.Method.invoke(Method.java:497)

ERROR RequestId:e96a7360-f18b-481a-95e6-bd298f556ab6 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"java.lang.reflect.InvocationTargetException","statusCode":430}

END RequestId:e96a7360-f18b-481a-95e6-bd298f556ab6

Report RequestId:e96a7360-f18b-481a-95e6-bd298f556ab6 Duration:32464ms Memory:256MB MemUsage:164.687500MB

**Comment by JunzhouLiu** [comment]
更新至1.0.3即可解决此问题
